
module.exports = {
  ERROR_WRONG,
  ERROR_INCORRECT_CODE,
  ERROR_USER_EXIST,
  ERROR_USER_NOT_EXIST,
  ERROR_ACCESS_DENIED,
  ERROR_EXIST_EMAIL,
  ERROR_EXIST_PHONE,

  ERROR_EMPTY,
  ERROR_INCORRECT_PASSWORD,
  ERROR_INCORRECT_URL,
  ERROR_INCORRECT_ID
};